name: Setup IRC channels

on:
  workflow_dispatch:
    inputs:
      slot:
        description: 'Slot start time of sessions to initialize (e.g. "9:30"), or "all" to initialize sessions across slots. The job is intended to be run shortly before each slot to init RRSAgent and Zakim. The "all" choice is probably not a good idea unless you also specify a session number: IRC bots leave channels after 2 hours of inactivity!'
        required: true
        type: string
      sessionNumber:
        description: 'Session issue number or "all" to initialize IRC channels for all valid sessions in the slot.'
        required: true
        default: 'all'
        type: string
      dismiss:
        description: 'Setup channel, or dismiss bots'
        required: true
        default: 'setup'
        type: choice
        options:
          - setup
          - dismiss

jobs:
  update-calendar:
    name: Setup IRC channels
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout latest version of release script
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install dependencies
        run: npm ci

      - name: Run the setup script
        run: node tools/setup-irc.mjs ${{ inputs.slot }} ${{ inputs.sessionNumber }} full ${{ inputs.dismiss }}
        env:
          # URL of the annual TPAC XXXX breakout project.
          # The PROJECT_OWNER and PROJECT_NUMBER variables must be defined on
          # the repository. PROJECT_OWNER_TYPE needs to be set to "user" if
          # project belongs to a user. It may be omitted otherwise (or set to
          # 'org"').
          PROJECT_OWNER: ${{ vars.PROJECT_OWNER_TYPE || 'organization' }}/${{ vars.PROJECT_OWNER || 'w3c' }}
          PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}

          # A valid Personal Access Token (classic version) with project
          # and public_repo scope.
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}

          # Mapping between chair GitHub identities and W3C IDs must be stored
          # in a variable. Structure is a JSON object with identities as keys.
          CHAIR_W3CID: ${{ vars.CHAIR_W3CID }}

